# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-19 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181019_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(max_length=400),
        ),
    ]
